apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: knative-serving
  labels:
    app.kubernetes.io/version: devel
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: knative-serving
  annotations:
    knative.dev/example-checksum: "b0f3c6f2"
data:  
  # Common configuration for all Knative codebase
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "timestamp",
        "levelKey": "severity",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "message",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
  # Log level overrides
  # For all components except the queue proxy,
  # changes are picked up immediately.
  # For queue proxy, changes require recreation of the pods.
  loglevel.controller: "info"
  loglevel.autoscaler: "info"
  loglevel.queueproxy: "info"
  loglevel.webhook: "info"
  loglevel.activator: "info"
  loglevel.hpaautoscaler: "info"
  loglevel.net-certmanager-controller: "info"
  loglevel.net-istio-controller: "info"
  loglevel.net-contour-controller: "info"