kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metatdata:
  name: sample-rolebinding
  namespace: demo
subjects:
  kind: ServiceAccount
  name: default
  namespace: demo
roleRef:
  kind: ClusterRole
  name: kubeflow-admin
  apiGroup: rbac.authorization.k8s.io