apiVersion: kubeflow.tmax.io/v1
kind: Notebook
metadata:
  labels:
    app: demo-notebook
  name: demo-notebook
  namespace: demo
spec:
  template:
    spec:
      containers:
        - env:
            ## 폐쇄망 registry 주소 (수정 필요)
          - name: REGISTRY
            value: "192.168.6.181:5000"
          ## notebook image 정의 (수정 필요)
          image: '192.168.6.181:5000/tmaxcloudck/kubeflow-jupyter-lab:v0.1'
          name: demo
          resources:
            ## notebook 사양 정의
            requests:
              cpu: "0.5"
              memory: 1.0Gi
          volumeMounts:
            - mountPath: /home/jovyan
              name: demo-pvc
            - mountPath: /dev/shm
              name: dshm      
      ## 사용할 volume 정의
      volumeMounts:
        - mountPath: /home/jovyan
          name: demo-pvc
        - mountPath: /dev/shm
          name: dshm
        - mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
          name: default-editor-token
          readOnly: true
      ## 사용할 volume 정의
      volumes:
      - name: demo-pvc
        persistentVolumeClaim:
          claimName: demo-pvc
      - emptyDir:
          medium: Memory
        name: dshm
      - name: default-editor-token
        secret:
          defaultMode: 420
          secretName: default-editor-token
  ## 사용할 volumeClaim 정의 : 없으면 새로 pvc를 생성      
  volumeClaim:
  - name: demo-pvc
    size: 10Gi
---
## serviceaccount token 수동마운트를 위한(secret name 난수 x) secret 수동 생성
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default-editor
  name: default-editor-token
  ## profile로 생성한 namespace와 동일해야함
  namespace: demo
type: kubernetes.io/service-account-token
