apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:  
  name: mnist-e2e
  namespace: demo  
spec:
  algorithm:
    algorithmName: random
  maxFailedTrialCount: 3
  maxTrialCount: 5
  metricsCollectorSpec:
    collector:
      kind: StdOut
  objective:
    goal: 0.001
    metricStrategies:
    - name: loss
      value: min
    objectiveMetricName: loss
    type: minimize
  parallelTrialCount: 2
  parameters:
  - feasibleSpace:
      max: "0.05"
      min: "0.01"
    name: learning_rate
    parameterType: double
  - feasibleSpace:
      max: "100"
      min: "80"
    name: batch_size
    parameterType: int
  resumePolicy: LongRunning
  trialTemplate:
    failureCondition: status.conditions.#(type=="Failed")#|#(status=="True")#
    primaryContainerName: tensorflow
    primaryPodLabels:
      training.kubeflow.org/job-role: master
    successCondition: status.conditions.#(type=="Succeeded")#|#(status=="True")#
    trialParameters:
    - description: Learning rate for the training model
      name: learningRate
      reference: learning_rate
    - description: Batch size for the model
      name: batchSize
      reference: batch_size
    trialSpec:
      apiVersion: kubeflow.org/v1
      kind: TFJob
      spec:
        tfReplicaSpecs:
          Chief:
            replicas: 1
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                containers:
                - command:
                  - python
                  - /opt/model.py
                  - --tf-train-steps=200
                  - --tf-learning-rate=${trialParameters.learningRate}
                  - --tf-batch-size=${trialParameters.batchSize}
                  image: docker.io/liuhougangxa/tf-estimator-mnist
                  name: tensorflow
          Worker:
            replicas: 1
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                containers:
                - command:
                  - python
                  - /opt/model.py
                  - --tf-train-steps=200
                  - --tf-learning-rate=${trialParameters.learningRate}
                  - --tf-batch-size=${trialParameters.batchSize}
                  image: docker.io/liuhougangxa/tf-estimator-mnist
                  name: tensorflow
