apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: demo
  name: demo-experiment
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy      
      - loss
      - Validation-loss
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: "/result/mnist.log"
        kind: File
    collector:
      kind: File    
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: --dropout_rate
      parameterType: double
      feasibleSpace:
        min: "0.1"
        max: "0.9"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: --learning_rate
      - name: dropoutRate
        description: Dropout rate for the training model
        reference: --dropout_rate         
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: docker.io/rhojw/sample-job:3C8CE2EE
                command:
                  - "python"
                  - "/app/fmnist-save-model-renew.py"    
                  - "--learning_rate=${trialParameters.learningRate}"
                  - "--dropout_rate=${trialParameters.dropoutRate}"              
            restartPolicy: Never
