apiVersion: kubeflow.org/v1
kind: TFJob
metadata:  
  name: mnist-e2e
  namespace: demo  
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - args:
            - python /opt/model.py --tf-export-dir=/mnt/export --tf-train-steps=200
              --tf-learning-rate=0.04880357831441027 --tf-batch-size=86
            command:
            - sh
            - -c
            image: docker.io/liuhougangxa/tf-estimator-mnist
            name: tensorflow
            volumeMounts:
            - mountPath: /mnt/export
              name: model-volume
          volumes:
          - name: model-volume
            persistentVolumeClaim:
              claimName: end-to-end-pipeline-model-volume
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - args:
            - python /opt/model.py --tf-export-dir=/mnt/export --tf-train-steps=200
              --tf-learning-rate=0.04880357831441027 --tf-batch-size=86
            command:
            - sh
            - -c
            image: docker.io/liuhougangxa/tf-estimator-mnist
            name: tensorflow

