apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:  
  name: mnist-e2e
  namespace: demo
spec:
  predictor:
  ## inference server 정의
    tensorflow:      
      ## Model 위치 설정
      storageUri: pvc://end-to-end-pipeline-model-volume/