apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: demo
  annotations:
    serving.kserve.io/s3-region: us-west-2
    serving.kserve.io/s3-usevirtualbucket: "false"
    serving.kserve.io/s3-endpoint: minio-service.kubeflow.svc.cluster.local:9000 # replace with your s3 endpoint
    serving.kserve.io/s3-usehttps: "0" # by default 1, for testing with minio you need to set to 0
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=

